# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 00:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='source',
            field=models.CharField(choices=[('GC', 'Environment Canada')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='station_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
