# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-06 22:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20181006_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='first_year',
            new_name='data_end',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='last_year',
            new_name='data_start',
        ),
    ]
