# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20181117_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('min_temp', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('mean_temp', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('snow', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('total_percipitation', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('snow_on_ground', models.NullBooleanField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Station')),
            ],
        ),
    ]
