# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_dailyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='max_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='mean_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='min_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='rain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='snow',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='total_percipitation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
