# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='has_daily_data',
            field=models.BooleanField(default=False),
        ),
    ]
