# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20181120_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='snow_on_ground',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
