# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_station_has_daily_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='daily_percip_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='daily_record_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='daily_temp_count',
            field=models.IntegerField(null=True),
        ),
    ]
