# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-17 19:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20190217_2332'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['station', 'date'], name='weather_dai_station_db519d_idx'),
        ),
    ]
