# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-05 01:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_projectgrouping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgrouping',
            name='trend_line_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectgrouping',
            name='trend_line_low',
            field=models.IntegerField(null=True),
        ),
    ]
