# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_auto_20190505_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_zoom',
            field=models.IntegerField(null=True),
        ),
    ]
