# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_project_default_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
