# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-08-22 20:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_auto_20190616_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='source',
            field=models.CharField(choices=[('GC', 'Environment Canada'), ('CD', 'Climate Data'), ('GHCND', 'Global Historical Climatology Network')], max_length=10),
        ),
    ]
