# Generated by Django 5.0 on 2025-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_auto_20210822_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('GC', 'Environment Canada'), ('CD', 'Climate Data'), ('GHCND', 'Global Historical Climatology Network')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('load_from_date', models.DateField()),
                ('load_to_date', models.DateField()),
                ('stations_processed', models.IntegerField(default=0)),
                ('stations_skipped', models.IntegerField(default=0)),
                ('stations_failed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
